version: "2"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  dbseed:
    build:
      context: ./src/data
      dockerfile: Dockerfile
    links:
      - mongo