version: "2"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - ./mongo-volume:/data/mongo
  dbseed:
    build:
      context: ./src/data
      dockerfile: Dockerfile
    links:
      - mongo
    depends_on:
      - mongo